---
AWSTemplateFormatVersion: "2010-09-09"
Description: "My Second cloudformation exercise"
Mappings: 
  SubnetConfig:
    VPC:
      CIDR: "10.50.0.0/16"
    Subnet1:
      CIDR: "10.50.1.0/24"
Resources: 
  CFVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      CidrBlock: !FindInMap [SubnetConfig, VPC, CIDR]
      Tags:
        - Key: Name
          Value: CFMyVPC
  CFSubnetA:
    Type: "AWS::EC2::Subnet"
    Properties: 
      AvailabilityZone: !Select [0,!GetAZs ]
      CidrBlock: !FindInMap [ SubnetConfig , Subnet1, CIDR ]
      VpcId: !Ref CFVPC
      Tags:
        - Key: Name
          Value: Mysubnet1
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: CFVPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
      # Notice how you can't attach an IGW to a VPC unless both are created:
    Properties:
      VpcId: !Ref CFVPC
      InternetGatewayId: !Ref InternetGateway
      

